-- RoS-Tools/Core/Config.lua
-- SavedVariables hold settings, plus at most one adopted roster snapshot
-- (`syncedData`, written by Core/Sync.lua). The item level table itself
-- ships in Data/GuildData.lua and is regenerated by the exporter; nothing
-- else is persisted here. An adopted snapshot is the one exception, and it
-- earns it by carrying its own generated_epoch and being dropped
-- automatically the moment the shipped file is newer -- see the source
-- selection in Core/Data.lua. 2.0 removed *unversioned* persisted data,
-- and that stays removed.
--
-- syncedData is deliberately absent from DEFAULTS: it is data, not a
-- setting, and it must not show up in `/ros set`.

local _, ns = ...

local DEFAULTS = {
  enabled        = true,   -- master switch for tooltip injection
  showTimestamp  = true,   -- show export date under the ilvl line
  showStaleWarn  = true,   -- warn in the tooltip when data is old
  staleDays      = 14,     -- days before data is considered stale
  colorByIlvl    = true,   -- color the number by threshold
  showDelta      = false,  -- show +/- vs. your own equipped ilvl
  rosterColumn   = true,   -- append ilvl in the guild/community roster
  rosterTooltip  = true,   -- ilvl in the hover tooltip over a roster row
  chatTooltip    = true,   -- ilvl when hovering a player name in chat
  suppressInCombat = false,-- hide the line while in combat
  commEnabled    = true,   -- live ilvl updates from online guildmates via addon comm
  commBroadcast  = true,   -- announce your own ilvl on change (off = receive only)
  syncEnabled    = true,   -- roster snapshot sync with guildmates (gates both directions)
  syncShare      = true,   -- serve your snapshot when asked (off = receive only)
  syncNotify     = true,   -- print a line when a newer roster is adopted
  debug          = false,
}

ns.DEFAULTS = DEFAULTS

-- Ordered thresholds, highest first. First match wins.
ns.ILVL_COLORS = {
  { min = 700, hex = "|cffff8000" }, -- legendary orange
  { min = 675, hex = "|cffa335ee" }, -- epic purple
  { min = 650, hex = "|cff0070dd" }, -- rare blue
  { min = 600, hex = "|cff1eff00" }, -- uncommon green
  { min = 0,   hex = "|cffffffff" }, -- white
}

function ns.ColorForIlvl(ilvl)
  if not (ns.db and ns.db.colorByIlvl) then return ns.COLOR.value end
  for i = 1, #ns.ILVL_COLORS do
    local tier = ns.ILVL_COLORS[i]
    if ilvl >= tier.min then return tier.hex end
  end
  return ns.COLOR.value
end

--- The rendered item level: colored by tier, optionally suffixed with the
--- delta against your own equipped item level. Every surface that prints a
--- number goes through here so they can't drift apart.
function ns.IlvlText(ilvl)
  local text = ns.ColorForIlvl(ilvl) .. ilvl .. ns.COLOR.reset

  if ns.db and ns.db.showDelta and ns.Data then
    local mine = ns.Data:PlayerIlvl()
    if mine then
      local delta = ilvl - mine
      if delta ~= 0 then
        local color = delta > 0 and "|cffff6666" or "|cff66ff66"
        text = ("%s %s%+d%s"):format(text, color, delta, ns.COLOR.reset)
      end
    end
  end

  return text
end

function ns.LoadConfig()
  if type(RoSToolsDB) ~= "table" then RoSToolsDB = {} end
  for k, v in pairs(DEFAULTS) do
    if RoSToolsDB[k] == nil then RoSToolsDB[k] = v end
  end
  ns.db = RoSToolsDB
  return ns.db
end

--- Toggle or set a boolean setting. Returns the new value.
--- Toggle or set a setting. The type check is not pedantry: a string
--- stored in a numeric option (`/ros set staleDays soon`) persists to
--- SavedVariables and then throws on every comparison -- at login, and on
--- every player tooltip -- until the user hand-edits the file.
function ns.SetOption(key, value)
  local default = DEFAULTS[key]
  if default == nil then return nil, "unknown option" end

  if value == nil then
    if type(default) ~= "boolean" then
      return nil, "needs a value"
    end
    value = not ns.db[key]
  end

  if type(value) ~= type(default) then
    return nil, ("expected %s"):format(type(default))
  end

  ns.db[key] = value
  return value
end
