-- RoS-Tools/Data/GuildData.lua
-- AUTO-GENERATED by Tools/fetch_guild_info.py -- DO NOT EDIT BY HAND.

local _, ns = ...

ns.GuildData = {
  meta = {
    generated_epoch = 1787509007,
    generated_at = "2026-08-23 18:16:47",
    region = "us",
    realm = "khadgar",
    guild = "riddle-of-steel",
    schema = 3,
  },
  ilvls = {
  },
}
