using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace RoSTools.Sidecar.Core.Blizzard;

public sealed record RosterEntry(string Key, int Ilvl);

/// <summary>
/// Emits <c>Data/GuildData.lua</c> in exactly the shape
/// <c>Tools/fetch_guild_info.py</c> produces.
/// <para>
/// "Exactly" is load-bearing, not tidiness. <see cref="GuildDataValidator"/>
/// compares every file against a fixed skeleton -
/// <c>local _, ns = ... ns.GuildData = { meta = {#}, ilvls = {#}, }</c> - and
/// refuses anything else, so a locally written file that drifts from the CI
/// exporter's layout is rejected by this machine's own installer and, worse, by
/// every guildmate's <c>Core/Sync.lua</c>. <c>GuildDataWriterTests</c> round-trips
/// this output through the real validator to keep the two honest.
/// </para>
/// </summary>
public static partial class GuildDataWriter
{
    /// <summary>
    /// LF, never the platform default. This file is read by WoW's Lua and diffed
    /// against the CI export; CRLF would change every line of that diff and, in the
    /// header comment, is exactly the damage the skeleton check exists to catch.
    /// </summary>
    private const string Newline = "\n";

    private const string Header =
        "-- RoS-Tools/Data/GuildData.lua" + Newline +
        "-- AUTO-GENERATED by the RoS-Tools Sidecar -- DO NOT EDIT BY HAND." + Newline +
        Newline +
        "local _, ns = ..." + Newline +
        Newline +
        "ns.GuildData = {" + Newline +
        "  meta = {" + Newline +
        "    -- generated_epoch is the authority: a plain UTC epoch, so the addon can" + Newline +
        "    -- age the data without knowing what zone this machine was in." + Newline +
        "    -- generated_at is the same instant rendered as UTC, kept for humans" + Newline +
        "    -- reading the file and as the fallback for schema 2 readers." + Newline;

    /// <summary>Matches the exporter's <c>schema = 3</c>. Bump both together.</summary>
    public const int Schema = 3;

    /// <summary>
    /// Renders the file. Keys that <c>Core/Sync.lua</c> could not carry are dropped
    /// and reported through <paramref name="dropped"/> rather than written.
    /// <para>
    /// Dropping beats emitting: the validator rejects a file with one unusable key
    /// outright, so writing it would cost the whole roster to save one member. The
    /// caller surfaces the count, so this is never silent.
    /// </para>
    /// </summary>
    public static string Render(
        IEnumerable<RosterEntry> entries,
        GuildIdentity identity,
        long generatedEpoch,
        out IReadOnlyList<string> dropped)
    {
        var rejected = new List<string>();
        var usable = new List<RosterEntry>();
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var entry in entries)
        {
            if (!IsUsableKey(entry.Key) || entry.Ilvl is < 1 or > 9999)
            {
                rejected.Add(entry.Key);
                continue;
            }

            // The API can list the same character twice across connected realms. A
            // duplicate key is a hard validator failure, so collapse here and keep the
            // higher item level rather than losing the file.
            if (!seen.Add(entry.Key))
            {
                var index = usable.FindIndex(e => string.Equals(e.Key, entry.Key, StringComparison.Ordinal));
                if (index >= 0 && entry.Ilvl > usable[index].Ilvl)
                {
                    usable[index] = entry;
                }

                continue;
            }

            usable.Add(entry);
        }

        dropped = rejected;

        var generatedAt = DateTimeOffset
            .FromUnixTimeSeconds(generatedEpoch)
            .UtcDateTime
            .ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);

        var builder = new StringBuilder(Header);

        builder
            .Append("    generated_epoch = ")
            .Append(generatedEpoch.ToString(CultureInfo.InvariantCulture))
            .Append(',').Append(Newline)
            .Append("    generated_at = \"").Append(generatedAt).Append("\",").Append(Newline)
            .Append("    region = \"").Append(identity.Region).Append("\",").Append(Newline)
            .Append("    realm = \"").Append(identity.Realm).Append("\",").Append(Newline)
            .Append("    guild = \"").Append(identity.Guild).Append("\",").Append(Newline)
            .Append("    schema = ").Append(Schema).Append(',').Append(Newline)
            .Append("  },").Append(Newline)
            .Append("  ilvls = {").Append(Newline);

        foreach (var entry in Sort(usable))
        {
            builder
                .Append("    [\"").Append(entry.Key).Append("\"] = ")
                .Append(entry.Ilvl.ToString(CultureInfo.InvariantCulture))
                .Append(',').Append(Newline);
        }

        builder.Append("  },").Append(Newline).Append('}').Append(Newline);

        return builder.ToString();
    }

    /// <summary>
    /// Writes UTF-8 without a BOM. <see cref="GuildDataValidator"/> tolerates one
    /// and WoW's Lua does not, so this is the side that matters.
    /// </summary>
    public static void WriteTo(string path, string content)
    {
        var directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllBytes(path, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(content));
    }

    /// <summary>
    /// Ordering matches the Python exporter's
    /// <c>sorted(key=lambda c: NFKD(c.key).lower())</c>, so a sidecar pull and a CI
    /// export of the same roster diff to nothing but the epoch.
    /// </summary>
    private static IEnumerable<RosterEntry> Sort(List<RosterEntry> entries) =>
        entries.OrderBy(
            e => e.Key.Normalize(NormalizationForm.FormKD).ToLowerInvariant(),
            StringComparer.Ordinal);

    /// <summary>
    /// The same bar <c>Core/Sync.lua</c>'s <c>validKey</c> sets, and the one
    /// <see cref="GuildDataValidator"/> enforces: no separator or markup characters,
    /// a realm suffix, and 48 bytes at most.
    /// </summary>
    public static bool IsUsableKey(string key) =>
        !string.IsNullOrEmpty(key) &&
        Encoding.UTF8.GetByteCount(key) <= 48 &&
        // '"' and '\' would need escaping, and the validator's entry pattern reads
        // the key as [^"\r\n]* -- an escaped quote inside it is unparseable there
        // even though Lua itself would accept it.
        !key.Contains('"') && !key.Contains('\\') &&
        SyncKeyShape().IsMatch(key);

    [GeneratedRegex(@"\A[^\t\n\v\f\r :;=|]+-[A-Za-z0-9-]+\z")]
    private static partial Regex SyncKeyShape();
}
