#!/usr/bin/env python3
"""Regenerate Data/GuildData.lua from the Blizzard Community API.

Usage
-----
    python fetch_guild_info.py --realm khadgar --guild "Riddle of Steel"

Credentials come from the environment (preferred) or --client-id /
--client-secret:

    BLIZZARD_CLIENT_ID
    BLIZZARD_CLIENT_SECRET

Create an application at https://develop.battle.net/access/clients to get
them. The client credentials flow needs no redirect URI and no user
consent -- it only reads public profile data.
"""

from __future__ import annotations

import argparse
import concurrent.futures as futures
import os
import re
import sys
import time
import unicodedata
from dataclasses import dataclass
from pathlib import Path

try:
    import requests
except ImportError:  # pragma: no cover
    sys.exit("This script needs 'requests'. Install it with: pip install requests")


API_HOST = "https://{region}.api.blizzard.com"
OAUTH_HOST = "https://oauth.battle.net/token"
DEFAULT_WORKERS = 8
RETRY_STATUS = {429, 500, 502, 503, 504}


# ----------------------------------------------------------------------
# Slug helpers -- must stay in sync with Core/Util.lua RealmToSlug()
# ----------------------------------------------------------------------
def slugify(value: str) -> str:
    value = value.replace("\u2019", "").replace("'", "").replace("`", "")
    value = re.sub(r"\s+", "-", value.strip())
    value = re.sub(r"-+", "-", value)
    return value.lower()


@dataclass
class Character:
    name: str
    realm_slug: str
    ilvl: int

    @property
    def key(self) -> str:
        return f"{self.name}-{self.realm_slug}"


# ----------------------------------------------------------------------
# API client
# ----------------------------------------------------------------------
class BlizzardClient:
    def __init__(self, client_id: str, client_secret: str, region: str = "us"):
        self.region = region
        self.session = requests.Session()
        self.session.headers["Accept"] = "application/json"
        self._authenticate(client_id, client_secret)

    def _authenticate(self, client_id: str, client_secret: str) -> None:
        response = requests.post(
            OAUTH_HOST,
            data={"grant_type": "client_credentials"},
            auth=(client_id, client_secret),
            timeout=30,
        )
        response.raise_for_status()
        token = response.json()["access_token"]
        self.session.headers["Authorization"] = f"Bearer {token}"

    def get(self, path: str, namespace: str, **params):
        url = API_HOST.format(region=self.region) + path
        params.setdefault("locale", "en_US")
        params["namespace"] = f"{namespace}-{self.region}"

        for attempt in range(5):
            response = self.session.get(url, params=params, timeout=30)

            if response.status_code == 404:
                return None
            if response.status_code in RETRY_STATUS:
                time.sleep(2 ** attempt * 0.25)
                continue

            response.raise_for_status()
            return response.json()

        return None

    def guild_roster(self, realm_slug: str, guild_slug: str):
        data = self.get(
            f"/data/wow/guild/{realm_slug}/{guild_slug}/roster",
            namespace="profile",
        )
        return (data or {}).get("members", [])

    def character_ilvl(self, realm_slug: str, name: str):
        data = self.get(
            f"/profile/wow/character/{realm_slug}/{name.lower()}",
            namespace="profile",
        )
        if not data:
            return None
        return data.get("equipped_item_level") or data.get("average_item_level")


# ----------------------------------------------------------------------
# Lua emitter
# ----------------------------------------------------------------------
LUA_HEADER = """\
-- Riddled/Data/GuildData.lua
-- AUTO-GENERATED by Tools/fetch_guild_info.py -- DO NOT EDIT BY HAND.

local _, ns = ...

ns.GuildData = {{
  meta = {{
    generated_at = "{generated_at}",
    region = "{region}",
    realm = "{realm}",
    guild = "{guild}",
    schema = 2,
  }},
  ilvls = {{
"""

LUA_FOOTER = """  },
}
"""


def escape_lua(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def write_lua(path: Path, characters: list[Character], meta: dict) -> None:
    characters = sorted(characters, key=lambda c: unicodedata.normalize("NFKD", c.key).lower())

    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(LUA_HEADER.format(**meta))
        for character in characters:
            handle.write(f'    ["{escape_lua(character.key)}"] = {character.ilvl},\n')
        handle.write(LUA_FOOTER)


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--region", default="us")
    parser.add_argument("--realm", required=True, help="Guild's home realm, e.g. khadgar")
    parser.add_argument("--guild", required=True, help='Guild name, e.g. "Riddle of Steel"')
    parser.add_argument("--min-level", type=int, default=1,
                        help="Skip characters below this level")
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS)
    parser.add_argument("--client-id", default=os.environ.get("BLIZZARD_CLIENT_ID"))
    parser.add_argument("--client-secret", default=os.environ.get("BLIZZARD_CLIENT_SECRET"))
    parser.add_argument("--out", type=Path,
                        default=Path(__file__).resolve().parent.parent / "Data" / "GuildData.lua")
    args = parser.parse_args()

    if not args.client_id or not args.client_secret:
        return parser.error(
            "Missing credentials. Set BLIZZARD_CLIENT_ID and BLIZZARD_CLIENT_SECRET, "
            "or pass --client-id/--client-secret."
        )

    realm_slug = slugify(args.realm)
    guild_slug = slugify(args.guild)

    client = BlizzardClient(args.client_id, args.client_secret, args.region)

    print(f"Fetching roster for {guild_slug} on {realm_slug} ({args.region})...")
    members = client.guild_roster(realm_slug, guild_slug)
    if not members:
        print("No roster returned. Check the realm and guild names.", file=sys.stderr)
        return 1

    targets = []
    for member in members:
        character = member.get("character", {})
        name = character.get("name")
        level = character.get("level", 0)
        member_realm = character.get("realm", {}).get("slug", realm_slug)
        if name and level >= args.min_level:
            targets.append((name, member_realm))

    print(f"{len(targets)} characters to query...")

    results: list[Character] = []
    failures = 0

    def fetch(target):
        name, member_realm = target
        try:
            ilvl = client.character_ilvl(member_realm, name)
        except requests.RequestException:
            return None
        if not ilvl:
            return None
        return Character(name=name, realm_slug=member_realm, ilvl=int(ilvl))

    with futures.ThreadPoolExecutor(max_workers=args.workers) as pool:
        for index, character in enumerate(pool.map(fetch, targets), start=1):
            if character:
                results.append(character)
            else:
                failures += 1
            if index % 25 == 0:
                print(f"  {index}/{len(targets)}")

    meta = {
        "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "region": args.region,
        "realm": realm_slug,
        "guild": guild_slug,
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    write_lua(args.out, results, meta)

    print(f"\nWrote {len(results)} entries to {args.out}")
    if failures:
        print(f"{failures} characters skipped (private profile, never logged in, or API error)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
